sourceflag:
  agile:
    logger:
      enable: true
      logger:
        log-mode: log
        curl-enable: true
        response-success-define:
          code-fields:
            - name: code
              value: 200
            - name: code
              value: 100
          message-fields: message, msg
      async:
        enable: true
        async-params:
          core-pool-size: 1
          maximum-pool-size: 2
          keep-alive-time: 60s
          queue-size: 1024
    idempotent:
      enable: true
      message: "接口幂等，无法提交"
    limiter:
      enable: true
      message: "接口限流，无法提交"
    database:
      enable: true
      show-sql: true
      ddl-auto: update
      format-sql: true
      delete-column: true
    workflow:
      ddl-auto: update
    annotation-scanner:
      enable: true
      annotation-class-names:
        - org.springframework.web.bind.annotation.CrossOrigin
        - org.springframework.web.bind.annotation.RestController
    wechat:
      mini:
        enable: true
        app-id: wxdc5814ab8fad0908
        app-secret: ee1a1a02cd51887054f1f7f8ec4bd042
        message-push:
          token: 123456
          encoding-aes-key: m20QJDz5tU4vMD2oskWH5TZv2kCfkV5l7ma68Tubmrq
          encrypt-type: ciphertext
          message-type: xml
      third:
        enable: true
        component-app-id: 123456789
        component-app-secret: 123456789
        verify-token: 123456789
        encrypt-aes-key: 123456789

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG