package io.github.thebesteric.framework.agile.plugins.database.core.domain;

import lombok.Getter;

@Getter
public enum DatabaseProduct {
    MYSQL("MySQL"), POSTGRESQL("PostgreSQL");

    private final String databaseProductName;

    DatabaseProduct(String databaseProductName) {
        this.databaseProductName = databaseProductName;
    }

    public static DatabaseProduct of(String databaseProductName) {
        for (DatabaseProduct databaseProduct : DatabaseProduct.values()) {
            if (databaseProduct.databaseProductName.equalsIgnoreCase(databaseProductName)) {
                return databaseProduct;
            }
        }
        throw new IllegalArgumentException("Unsupported database product name: " + databaseProductName);
    }

    public String toDialect(String sql) {
        if (this == POSTGRESQL) {
            // 安全替换标识符符号
            sql = sql.replace("`", "\"");

            // 替换自增
            sql = sql.replaceAll("\\bAUTO_INCREMENT\\b", "GENERATED BY DEFAULT AS IDENTITY NOT NULL");
            // 替换时间类型
            sql = sql.replaceAll("\\bTIMESTAMP\\b", "TIMESTAMP WITHOUT TIME ZONE");
            sql = sql.replaceAll("\\bDATETIME\\b", "TIMESTAMP WITHOUT TIME ZONE");
            sql = sql.replaceAll("\\bFLOAT\\b", "NUMERIC");
            sql = sql.replaceAll("\\bDOUBLE\\b", "NUMERIC");
            sql = sql.replaceAll("\\bDECIMAL\\b", "NUMERIC");
            sql = sql.replaceAll("\\bTINYINT\\b", "SMALLINT");
            sql = sql.replaceAll("\\bTINYBLOB\\b", "BYTEA");
            sql = sql.replaceAll("\\bMEDIUMBLOB\\b", "BYTEA");
            sql = sql.replaceAll("\\bLONGBLOB\\b", "LOBS");
            sql = sql.replaceAll("\\bBLOB\\b", "BYTEA");

            // 替换字段修改语法
            sql = sql.replaceAll("\\bMODIFY COLUMN\\b", "ALTER COLUMN");
            // 替换删除约束语法
            sql = sql.replaceAll("\\DROP KEY\\b", "DROP CONSTRAINT");
            // 移除无符号标识
            sql = sql.replaceAll("\\bUNSIGNED\\b", "");

            // 移除存储引擎（ENGINE=InnoDB）
            sql = sql.replaceAll("\\s+ENGINE\\s*=\\s*\\w+", "");
            // 移除字符集（CHARSET/CHARACTER SET）
            sql = sql.replaceAll("\\s+CHARSET\\s*=\\s*\\w+", "");
            sql = sql.replaceAll("\\s+CHARACTER\\s+SET\\s*=\\s*\\w+", "");
            // 移除字段顺序关键字 FIRST/AFTER（PG 不支持调整字段物理顺序）
            sql = sql.replaceAll("\\s+FIRST\\b", "");
            sql = sql.replaceAll("\\s+AFTER\\s+\\w+", "");
        }
        return sql;
    }
}
